### ISSUE TITLE
Tests in Forked Project not working

### ISSUE THREAD

**Issue by theluk** [mixpanel/mixpanel-php#18]
Even though I ran `composer install` the tests are not running when using phpunit. It seams like they cannot even run as there is no phpunit.xml configuration file and no phpunit bootup file where you could autoload anything using composer.

**Comment by jbwyme** [comment]
Interesting, that first error seems like it may have to do with the error level being set to include "Notices". Let me check into these. Sorry for the delay, I never noticed an alert for this issue.
