### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by martindilling** [mixpanel/mixpanel-php#24]
I would just like to ask if this is still updated and supported?
It doesn't look like there are much activity, both in the code and the issues/pull requests :)

And would this package work with php7?

**Comment by jbboehr** [comment]
@martindilling I've been using it without problems. The unit tests are passing on PHP7, although it looks like the current master build failed due to downtime at GitHub: https://travis-ci.org/mixpanel/mixpanel-php/jobs/76002912#L293 https://status.github.com/messages/2015-08-18

**Comment by zakj** [comment]
Hey @martindilling, yes we do still support this library! Please feel free to open an issue/PR if you have troubles getting it to work on php7, as I haven't personally run it in that environment aside from the tests.
