### ISSUE TITLE
No 'alias' api

### ISSUE THREAD

**Issue by scazzy** [mixpanel/mixpanel-php#26]
I don't find any 'alias' api. I want to use Mixpanel PHP api in background coming from an email pixel.
Without giving it an alias distinct_id, I cannot move forward.

**Comment by jbwyme** [comment]
https://github.com/mixpanel/mixpanel-php/blob/b89318bd02c77a18b9c8262f9afc7aef27e43dd3/examples/aliasing.php#L9
