### ISSUE TITLE
Library doesn't work with Laravel Framework (artisan queue:work)

### ISSUE THREAD

**Issue by soochanlee** [mixpanel/mixpanel-php#29]
Hi,

My name is Steve and I'm using Mixpanel for my company.

I emailed you because I need help.

My company uses Laravel Framework for API and Mixpanel for tracking.

It seems like mixpanel-php doesn't work with laravel Job.

I use track function inside laravel job which is running by php artisan queue:work

and I found that in Producer - Consumer model of mixpanel-php, Pruducer works correctly and put message in queue, but Consumer dosen't work so that queue is keep increasing.

I try making queue reach max size which is 1000 and it worked becase of force flush.

 I want to see the events realtime so cannot wait until queue reaches max size.

Is there any way to make consumer of mixpanel-php work on laravel job environment?

Thanks.

**Comment by abdallahhamdy** [comment]
@soochanlee as a work around try to set the max queue size to 0 when you are initializing mixpanel 
 "max_queue_size"    => 0
it worked for us

**Comment by jbwyme** [comment]
That's correct, setting the max_queue_size to 0 will force a flush with
every item added to the queue.
