### ISSUE TITLE
Getting currently assigned random ID

### ISSUE THREAD

**Issue by nWidart** [mixpanel/mixpanel-php#32]
Hello,

I'm starting out with Mixpanel. I'm currently facing the issue that starting the funnel a user is not logged in,  and once he logs in, I cannot link both events together.

I've read on using `alias`, I've also seen the example php file about aliasing in this repository. However I don't understand how to get the `original_id` that Mixpanel randomly created for the not logged in user.

Thank you,

**Comment by jringeisen** [comment]
@nWidart were you able to figure out a solution for this? I'm running into the same problem.
