### ISSUE TITLE
I cant set MIXPANEL PROPERTIES with Mixpanel Library:php  as Mixpanel Library: web (javascript lib)

### ISSUE THREAD

**Issue by vienle197** [mixpanel/mixpanel-php#44]
I cant set MIXPANEL PROPERTIES with Mixpanel Library:php  as Mixpanel Library: web (javascript lib): 
This is my MIXPANEL PROPERTIES  when i use lib php: 
![image](https://user-images.githubusercontent.com/33427571/45416348-f58a2600-b6a9-11e8-8f5b-922148cbb058.png)

And I want to like this by lib php not is lib web(js)
![image](https://user-images.githubusercontent.com/33427571/45416070-4cdbc680-b6a9-11e8-8e87-3a6c8e3b88a4.png)

Help me pls!!!

**Comment by zakj** [comment]
Hi @vienle197, unfortunately there's no way for our PHP library to reliably know data about the web client without you explicitly passing that data along. Feel free to write in to our excellent support staff if you need help with the specifics:

https://help.mixpanel.com/hc/en-us/requests/new
