### ISSUE TITLE
Laravel Integration

### ISSUE THREAD

**Issue by amelyec** [mixpanel/mixpanel-php#62]
Any one integrated this in Laravel?

**Comment by mt-gareth** [comment]
Yes I did, though I did not use much of Laravel while doing so, just standard PHP. I just made a helper class to load a singleton with my project token loaded into it and then used that singleton through out the app. Did you have any issues?

**Comment by aakarim** [comment]
Check out https://github.com/GeneaLabs/laravel-mixpanel
