### ISSUE TITLE
Mixpanel autoload?

### ISSUE THREAD

**Issue by nrbrook** [mixpanel/mixpanel-php#8]
I've installed the PHP library via Composer and I noticed that Mixpanel is set to load automatically when the composer autoloader is loaded, from composer.json:

"autoload": {
        "files": ["lib/Mixpanel.php"]
    }

This is not ideal because the Mixpanel class and all dependencies get automatically loaded all the time in my application, even if I want to do something completely unrelated to mixpanel.  Perhaps using [psr-0](http://getcomposer.org/doc/04-schema.md#psr-0) or [classmap](http://getcomposer.org/doc/04-schema.md#classmap) would be a better solution?  This would mean the class is only loaded when first used and additionally you will not need to manually require other classes in your library as you currently do.

**Comment by mihroot** [comment]
It would be great to see upgraded autoload ;).. +1
Now I need to override composer.json data, to make things work as supposed
